import Head from "next/head";
import Contact from "../components/layout/Contact";
import Projects from "../components/layout/Projects";
import About from "../components/main/About";
import Main from "../components/main/Main";
import Skills from "../components/main/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Milhas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
